# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Player.create(:name => "Ian", :email => "ian@mosaic.pe")
Player.create(:name => "Joanne", :email => "joanne@mosaic.pe")
Player.create(:name => "Elina", :email => "elina@mosaic.pe")
Player.create(:name => "Rona", :email => "rona@mosaic.pe")
Player.create(:name => "Tyler", :email => "tyler@mosaic.pe")
Player.create(:name => "Betty", :email => "betty@mosaic.pe")
Player.create(:name => "Luyi", :email => "luyi@mosaic.pe")
Player.create(:name => "Gaurav", :email => "gaurav@mosaic.pe")
Player.create(:name => "Dhruv", :email => "dhruv@mosaic.pe")
Player.create(:name => "Sidd", :email => "sidd@mosaic.pe")
Player.create(:name => "Peter", :email => "peter@mosaic.pe")
Player.create(:name => "Homer", :email => "homer@mosaic.pe")
Player.create(:name => "Charles", :email => "charles@mosaic.pe")
Player.create(:name => "Elaine", :email => "elaine@mosaic.pe")
Player.create(:name => "Will", :email => "will@mosaic.pe")
Player.create(:name => "Jacob", :email => "jacob@mosaic.pe")
Player.create(:name => "Jess", :email => "jess@mosaic.pe")
Player.create(:name => "Ethan", :email => "ethan@mosaic.pe")
Player.create(:name => "Claire", :email => "claire@mosaic.pe")
Player.create(:name => "Ryley", :email => "ryley@mosaic.pe")
Player.create(:name => "Sophie", :email => "sophie@mosaic.pe")
Player.create(:name => "Jordan", :email => "jordan@mosaic.pe")
Player.create(:name => "Julia", :email => "julia@mosaic.pe")
Player.create(:name => "Dany", :email => "dany@mosaic.pe")
Player.create(:name => "Steve", :email => "steve@mosaic.pe")
Player.create(:name => "Ize", :email => "ize@mosaic.pe")
Player.create(:name => "Tanner", :email => "tanner@mosaic.pe")
Player.create(:name => "Pauline", :email => "pauline@mosaic.pe")
Player.create(:name => "Gordon", :email => "gordon@mosaic.pe")
Player.create(:name => "Aggie", :email => "aggie@mosaic.pe")
